<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\ItemSetRepresentation $resource
 * @var \Omeka\Api\Representation\ItemSetRepresentation $itemSet
 * @var string $resourceType
 * @var array $data
 */

$translate = $this->plugin('translate');
?>
<div class="<?php echo $resourceType; ?>" id="<?php echo $resourceType . '-' . $resource->id(); ?>">
    <h2><?php echo sprintf($translate('Item set #%d'), $resource->id()); ?></h2>

    <?php echo $resource->displayValues(['viewName' => 'ebook/template/resource-values']); ?>

    <?php
    $subjectValues = $resource->displaySubjectValues();
    if ($subjectValues): ?>
    <div id="item-linked">
        <h3><?php echo $translate('Linked resources'); ?></h3>
        <?php echo $subjectValues; ?>
    </div>
    <?php endif; ?>
</div>