<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\ItemRepresentation $resource
 * @var \Omeka\Api\Representation\ItemRepresentation $itemSet
 * @var string $resourceType
 * @var array $data
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$embedMedia = !empty($data['item_media_embed']);
/** @var \Omeka\Api\Representation\MediaRepresentation[] $medias */
$medias = $item->media();
?>

<div class="<?php echo $resourceType; ?>" id="<?php echo $resourceType . '-' . $resource->id(); ?>">
    <h2><?php echo sprintf($translate('Item #%d'), $resource->id()); ?></h2>
    <?php if ($embedMedia && $medias): ?>
    <div class="media-embeds">
        <?php
        foreach ($medias as $media):
            // Manage only medias that can be displayed by an ebook.
            if (in_array($media->mediaType(), ['image/gif', 'image/png', 'image/jpeg'])):
                echo $media->render();
            else:
                echo $media->linkPretty();
            endif;
        endforeach;
        ?>
    </div>
    <?php endif; ?>

    <?php echo $resource->displayValues(['viewName' => 'ebook/template/resource-values']); ?>

    <div class="property">
        <?php $itemSets = $item->itemSets(); ?>
        <?php if (count($itemSets)): ?>
        <h4><?php echo $translate('Item sets'); ?></h4>
        <?php foreach ($item->itemSets() as $itemSet): ?>
        <div class="value">
            <?php echo $itemSet->displayTitle(); ?>
        </div>
        <?php endforeach; ?>
        <?php endif; ?>
    </div>

    <?php if (!$embedMedia && $medias): ?>
    <div class="media-list">
        <h4><?php echo $translate('Medias'); ?></h4>
        <?php foreach ($medias as $media): ?>
        <div class="value">
            <a class="resource-link" href="<?php echo $media->siteUrl($this->defaultSiteSlug(), true); ?>">
                <?php $title = $media->value('dcterms:title', ['type' => 'literal']); ?>
                <?php $title = $title ? $title->value() : sprintf($translate('Media #%d'), $media->id()); ?>
                <img src="<?php echo $media->thumbnailUrl('medium'); ?>" alt="<?php echo $title; ?>" />
                <span class="resource-name"><?php echo $title; ?></span>
            </a>
        </div>
        <?php endforeach; ?>
    </div>
    <?php endif; ?>

    <?php
    $subjectValues = $resource->displaySubjectValues();
    if ($subjectValues): ?>
    <div id="item-linked">
        <h3><?php echo $translate('Linked resources'); ?></h3>
        <?php echo $subjectValues; ?>
    </div>
    <?php endif; ?>
</div>
