<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\ItemSetRepresentation $resource
 * @var \Omeka\Api\Representation\ItemSetRepresentation $itemSet
 * @var string $resourceType
 * @var array $data
 */

$translate = $this->plugin('translate');
?>

<div class="<?= $resourceType; ?>" id="<?= $resourceType . '-' . $resource->id() ?>">
    <h2><?= sprintf($translate('Item set #%d'), $resource->id()) ?></h2>

    <?= $resource->displayValues(['viewName' => 'ebook/template/resource-values']) ?>

    <?php
    $subjectValues = $resource->displaySubjectValues();
    if ($subjectValues): ?>
    <div id="item-linked">
        <h3><?= $translate('Linked resources') ?></h3>
        <?= $subjectValues; ?>
    </div>
    <?php endif; ?>
</div>
