<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\ItemRepresentation $resource
 * @var \Omeka\Api\Representation\ItemRepresentation $item
 * @var \Omeka\Api\Representation\ItemSetRepresentation $itemSet
 * @var string $resourceType
 * @var array $data
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$embedMedia = !empty($data['item_media_embed']);
/** @var \Omeka\Api\Representation\MediaRepresentation[] $medias */
$medias = $item->media();
?>

<div class="<?= $resourceType ?>" id="<?= $resourceType . '-' . $resource->id() ?>">
    <h2><?= sprintf($translate('Item #%d'), $resource->id()) ?></h2>
    <?php if ($embedMedia && $medias): ?>
    <div class="media-embeds">
        <?php
        foreach ($medias as $media):
            // Manage only medias that can be displayed by an ebook.
            if (in_array($media->mediaType(), ['image/gif', 'image/png', 'image/jpeg'])):
                echo $media->render();
            else:
                echo $media->linkPretty();
            endif;
        endforeach;
        ?>
    </div>
    <?php endif; ?>

    <?= $resource->displayValues(['viewName' => 'ebook/template/resource-values']) ?>

    <div class="property">
        <?php $itemSets = $item->itemSets(); ?>
        <?php if (count($itemSets)): ?>
        <h4><?= $translate('Item sets') ?></h4>
        <?php foreach ($item->itemSets() as $itemSet): ?>
        <div class="value">
            <?= $itemSet->displayTitle() ?>
        </div>
        <?php endforeach; ?>
        <?php endif; ?>
    </div>

    <?php if (!$embedMedia && $medias): ?>
    <div class="media-list">
        <h4><?= $translate('Medias') ?></h4>
        <?php foreach ($medias as $media): ?>
        <div class="value">
            <a class="resource-link" href="<?= $media->siteUrl($this->defaultSiteSlug(), true) ?>">
                <?php $title = $media->value('dcterms:title', ['type' => 'literal']); ?>
                <?php $title = $title ? $title->value() : sprintf($translate('Media #%d'), $media->id()) ?>
                <img src="<?= $media->thumbnailUrl('medium') ?>" alt="<?= $title ?>" />
                <span class="resource-name"><?= $title ?></span>
            </a>
        </div>
        <?php endforeach; ?>
    </div>
    <?php endif; ?>

    <?php
    $subjectValues = $resource->displaySubjectValues();
    if ($subjectValues): ?>
    <div id="item-linked">
        <h3><?= $translate('Linked resources') ?></h3>
        <?= $subjectValues ?>
    </div>
    <?php endif; ?>
</div>
