<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\ValueRepresentation[] $values
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$labelInfo = $this->setting('property_label_information');
?>

<?php foreach ($values as /* $term => */ $propertyData): ?>
    <div class="property">
        <h4>
        <?php if ($propertyData['alternate_label']): ?>
        <?= $escape($propertyData['alternate_label']) ?>
        <?php else: ?>
        <?= $escape($translate($propertyData['property']->label())) ?>
        <?php endif; ?>
        <?php if ('term' === $labelInfo): ?>
        <span class="field-term">(<?= $escape($propertyData['property']->term()) ?>)</span>
        <?php elseif ('vocab' === $labelInfo): ?>
        <span class="field-term">(<?= $escape($propertyData['property']->vocabulary()->label()) ?>)</span>
        <?php endif; ?>
        </h4>
        <div class="values">
        <?php foreach ($propertyData['values'] as $value): ?>
            <?php
            $class = 'value';
            if ('resource' == $value->type()):
                $valueResource = $value->valueResource();
                $class .= ' resource ' . $escape($valueResource->resourceName());
            elseif ('uri' == $value->type()):
                $class .= ' uri';
            endif;
            ?>
            <div class="<?= $class; ?>" lang="<?= $escape($value->lang()) ?>">
                <?php /*
                <?php if ($language = $value->lang()): ?>
                <span class="language"><?= $language ?></span>
                <?php endif; ?>
                */ ?>
                <?= $value->asHtml() ?>
            </div>
        <?php endforeach; ?>
        </div>
    </div>
<?php endforeach; ?>
