<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Api\Representation\SitePageRepresentation $resource
 * @var \Omeka\Api\Representation\SitePageRepresentation $page
 * @var string $resourceType
 * @var array $data
 */

// $translate = $this->plugin('translate');

// Don't trigger events in the ebook.
?>

<div class="<?= $resourceType ?>" id="<?= $resourceType . '-' . $resource->id() ?>">
    <h2><?= $page->title() ?></h2>
    <?php // $this->trigger('view.show.before'); ?>
    <div class="blocks">
        <?= $this->content ?>
    </div>
    <?php // $this->trigger('view.show.after'); ?>
</div>
