<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Ebook\Form\EbookForm $form
 */

$translate = $this->plugin('translate');

$form->prepare();
$this->htmlElement('body')->appendAttribute('class', 'ebook create site');
?>

<?= $this->pageTitle($translate('Create an ebook for the site')) ?>

<?= $this->form()->openTag($form) ?>

<div id="page-actions">
    <input type="submit" name="batch_process" value="<?= $this->escapeHtml($translate('Build')) ?>">
</div>

<?= $this->formCollection($form, false) ?>
<?= $this->form()->closeTag() ?>
